import { generateHTML } from '../utils/htmlGenerator.js';
import stream from 'stream';
import { createRequire } from 'module';
import { normalizeDesignTheme } from '../utils/designSystem.js';

const require = createRequire(import.meta.url);
const archiverModule = require('archiver');
const archiver = archiverModule && archiverModule.default ? archiverModule.default : archiverModule;

class ExportService {
  /**
   * Generates a complete HTML string for the project
   */
  generateHTML(project) {
    try {
      if (!project) {
        throw new Error('Project is required to generate HTML');
      }
      return generateHTML(project);
    } catch (error) {
      console.error('[ExportService] Error generating HTML:', error.message);
      throw error;
    }
  }

  /**
   * Generates JSON representation of the project
   */
  generateJSON(project) {
    try {
      if (!project) {
        throw new Error('Project is required to generate JSON');
      }
      // Return project as-is; service images are no longer generated or stored
      return JSON.stringify(project, null, 2);
    } catch (error) {
      console.error('[ExportService] Error generating JSON:', error.message);
      throw error;
    }
  }

  /**
   * Generates a ZIP archive stream containing HTML, CSS (inline for now), and README
   */
  async generateZIP(project) {
    const normalizedProject = {
      ...project,
      theme: normalizeDesignTheme(project.theme),
    };

    // `archiver` can expose either a callable or a `create` factory depending on bundling/CJS/ESM.
    // Support both APIs to avoid "archiver is not a function" runtime errors.
    let archive;
    try {
      if (typeof archiver === 'function') {
        archive = archiver('zip', { zlib: { level: 9 } });
      } else if (archiver && typeof archiver.create === 'function') {
        archive = archiver.create('zip', { zlib: { level: 9 } });
      } else if (archiver && typeof archiver.ZipArchive === 'function') {
        archive = new archiver.ZipArchive({ zlib: { level: 9 } });
      } else if (archiver && typeof archiver.Archiver === 'function') {
        archive = new archiver.Archiver({ zlib: { level: 9 } });
      } else {
        console.error('export.service: unsupported archiver shape', Object.keys(archiver || {}));
        throw new Error('archiver is not a function');
      }
    } catch (err) {
      console.error('export.service: failed to initialize archiver', err && err.message);
      throw err;
    }

    // Create a pass-through stream to pipe the archive data
    const passThrough = new stream.PassThrough();
    
    // Pipe archive data to the file
    archive.pipe(passThrough);

    // 1. Add index.html
    const htmlContent = this.generateHTML(normalizedProject);
    archive.append(htmlContent, { name: 'index.html' });

    // 2. Add styles.css (optional if inline, but let's provide a basic one as requested)
    const primaryColor = normalizedProject.theme.colors.primary;
    const cssContent = `
/* Custom Styles for ${project.name} */
:root {
  --primary-color: ${primaryColor};
}
/* Additional styles can be loaded here. The main layout is in index.html */
    `;
    archive.append(cssContent, { name: 'styles.css' });

    // 3. Add README.md
    const readmeContent = `# ${project.name}
    
Generated by AI Website Builder.

## Contents
- index.html: Main website file
- styles.css: Custom stylesheet
- data.json: Project data

## Instructions
Simply open \`index.html\` in any web browser to view your website.
    `;
    archive.append(readmeContent, { name: 'README.md' });

    // 4. Add data.json
    archive.append(this.generateJSON(normalizedProject), { name: 'data.json' });

    // Forward archive errors to the passThrough stream
    archive.on('error', (err) => {
      passThrough.emit('error', err);
    });

    // Finalize the archive (we are done appending files)
    await archive.finalize();

    return passThrough;
  }
}

export default new ExportService();
